<?xml version="1.0" encoding="utf-8"?><Database Name="gamersdaily_dk_db" Class="ArbejdArbejdDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mssql1.unoeuro.com;Initial Catalog=gamersdaily_dk_db;User ID=gamersdaily_dk" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="gamersdaily_dk_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aaTexts" Member="aaTexts">
    <Type Name="aaText">
      <Column Name="TextName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TextContent" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.aaCategory" Member="aaCategories">
    <Type Name="aaCategory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryDescribtion" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Main" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Sub" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>