#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="gamersdaily_dk_db")]
	public partial class ArbejdArbejdDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertaaText(aaText instance);
    partial void UpdateaaText(aaText instance);
    partial void DeleteaaText(aaText instance);
    #endregion
		
		public ArbejdArbejdDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["gamersdaily_dk_dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ArbejdArbejdDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArbejdArbejdDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArbejdArbejdDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArbejdArbejdDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<aaText> aaTexts
		{
			get
			{
				return this.GetTable<aaText>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aaTexts")]
	public partial class aaText : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TextName;
		
		private string _TextContent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTextNameChanging(string value);
    partial void OnTextNameChanged();
    partial void OnTextContentChanging(string value);
    partial void OnTextContentChanged();
    #endregion
		
		public aaText()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TextName
		{
			get
			{
				return this._TextName;
			}
			set
			{
				if ((this._TextName != value))
				{
					this.OnTextNameChanging(value);
					this.SendPropertyChanging();
					this._TextName = value;
					this.SendPropertyChanged("TextName");
					this.OnTextNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextContent", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string TextContent
		{
			get
			{
				return this._TextContent;
			}
			set
			{
				if ((this._TextContent != value))
				{
					this.OnTextContentChanging(value);
					this.SendPropertyChanging();
					this._TextContent = value;
					this.SendPropertyChanged("TextContent");
					this.OnTextContentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
